//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLog.Vision
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION_TYPE
    {
        public ACTION_TYPE()
        {
            this.GLOBAL_AUDIT = new HashSet<GLOBAL_AUDIT>();
        }
    
        public string ACTION_TYPE_ID { get; set; }
        public string ACTION_TYPE_NAME { get; set; }
        public decimal IS_ACTIVE { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual ICollection<GLOBAL_AUDIT> GLOBAL_AUDIT { get; set; }
    }
}
