//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLog.Vision
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBAL_AUDIT
    {
        public GLOBAL_AUDIT()
        {
            this.GLOBAL_AUDIT_DATA = new HashSet<GLOBAL_AUDIT_DATA>();
        }
    
        public string ENTITY { get; set; }
        public string ACTION { get; set; }
        public string PRIMARY_KEY_VALS { get; set; }
        public string CHANGED_COLS_VAL { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public string WINDOWS_CREATED_BY { get; set; }
        public string WINDOWS_UPDATED_BY { get; set; }
        public string MACHINE_NAME { get; set; }
        public int GLOBAL_AUDIT_ID { get; set; }
        public string LOG_TYPE_ID { get; set; }
        public decimal RESULT { get; set; }
        public string EVENT_ORIGIN { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ACTION_TYPE ACTION_TYPE { get; set; }
        public virtual ICollection<GLOBAL_AUDIT_DATA> GLOBAL_AUDIT_DATA { get; set; }
        public virtual LOG_TYPE LOG_TYPE { get; set; }
    }
}
