//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanza.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisionDBModel : DbContext
    {
        public VisionDBModel()
            : base("name=VisionDBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SEC_GROUP> SEC_GROUP { get; set; }
        public virtual DbSet<SEC_GROUP_PERMISSION> SEC_GROUP_PERMISSION { get; set; }
        public virtual DbSet<SEC_PERMISSION> SEC_PERMISSION { get; set; }
        public virtual DbSet<SEC_USER> SEC_USER { get; set; }
        public virtual DbSet<SEC_USER_GROUP> SEC_USER_GROUP { get; set; }
    }
}
